use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::error::AlfError;
use crate::fsops::Fs;

/// `.alf/lock.toml` — exactly what was resolved and copied in (fact). Generated
/// by alf, never hand-edited.
#[derive(Debug, Serialize, Deserialize)]
pub struct Lock {
    pub lock_version: u32,
    pub catalog: CatalogRef,
    #[serde(rename = "skill", default)]
    pub skills: Vec<LockedSkill>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct CatalogRef {
    pub remote: String,
    pub commit: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockedSkill {
    pub name: String,
    pub version: String,
    pub hash: String,
    pub source: String,
}

impl Lock {
    pub fn new(remote: String, commit: String) -> Lock {
        Lock {
            lock_version: 1,
            catalog: CatalogRef { remote, commit },
            skills: Vec::new(),
        }
    }

    pub fn load(path: &Path) -> Result<Lock, AlfError> {
        let text = std::fs::read_to_string(path).map_err(|e| AlfError::Io {
            path: path.to_path_buf(),
            source: e,
        })?;
        toml::from_str(&text).map_err(|e| AlfError::TomlDe {
            path: path.to_path_buf(),
            source: e,
        })
    }

    /// Insert or replace a locked skill, keeping the list sorted by name.
    pub fn upsert(&mut self, locked: LockedSkill) {
        match self.skills.iter_mut().find(|s| s.name == locked.name) {
            Some(existing) => *existing = locked,
            None => self.skills.push(locked),
        }
        self.skills.sort_by(|a, b| a.name.cmp(&b.name));
    }

    pub fn save(&self, fs: &mut Fs, path: &Path) -> Result<(), AlfError> {
        let body = toml::to_string_pretty(self).map_err(|e| AlfError::TomlSer { source: e })?;
        let text = format!("# Generated by alf. Do not edit by hand.\n\n{body}");
        fs.write(path, &text)
    }
}
