use std::path::Path;

use crate::error::AlfError;
use crate::fsops::Fs;
use crate::skill::Skill;

/// The AGENTS.md template, embedded at compile time. `alf init` stamps it; the
/// first conversation in the repo completes its `<...>` sections.
pub const AGENTS_TEMPLATE: &str = include_str!("../templates/AGENTS.md");

/// The CLAUDE.md pointer for the `claude` target.
pub const CLAUDE_POINTER: &str = include_str!("../templates/CLAUDE.md");

/// Canonical skills directory, read natively by Antigravity, Cursor, Copilot.
pub const CANONICAL_SKILLS: &str = ".agents/skills";

/// Mirror skills directory, read by Claude Code. Regenerated by alf.
pub const CLAUDE_SKILLS: &str = ".claude/skills";

/// Lay down the full, uniform scaffold: AGENTS.md (only if absent, so a filled
/// file is never clobbered), the CLAUDE.md pointer (likewise), and each skill
/// copied into both the canonical and mirror directories.
pub fn write_scaffold(fs: &mut Fs, root: &Path, skills: &[Skill]) -> Result<(), AlfError> {
    fs.write_if_absent(&root.join("AGENTS.md"), AGENTS_TEMPLATE)?;
    fs.write_if_absent(&root.join("CLAUDE.md"), CLAUDE_POINTER)?;
    for skill in skills {
        install_skill(fs, root, skill)?;
    }
    Ok(())
}

/// Regenerate one skill's Claude mirror from the canonical copy already in the
/// project. Used by `plearn` after the agent edited the canonical skill.
pub fn regenerate_mirror(fs: &mut Fs, root: &Path, name: &str) -> Result<(), AlfError> {
    let canonical = root.join(CANONICAL_SKILLS).join(name);
    let mirror = root.join(CLAUDE_SKILLS).join(name);
    fs.remove_dir_all_if_exists(&mirror)?;
    fs.copy_dir(&canonical, &mirror)?;
    Ok(())
}

/// Install (or reinstall) one skill: copy it into the canonical directory and
/// regenerate its Claude mirror. Idempotent — the target dirs are cleared first.
pub fn install_skill(fs: &mut Fs, root: &Path, skill: &Skill) -> Result<(), AlfError> {
    let canonical = root.join(CANONICAL_SKILLS).join(&skill.name);
    let mirror = root.join(CLAUDE_SKILLS).join(&skill.name);

    fs.remove_dir_all_if_exists(&canonical)?;
    fs.copy_dir(&skill.dir, &canonical)?;

    fs.remove_dir_all_if_exists(&mirror)?;
    fs.copy_dir(&skill.dir, &mirror)?;
    Ok(())
}
